var Bill_Gen = {
    tarrifcode : String,
    txnconsumerid : String,
    txnmtrsrno : String,
    billstdate : String,
    billenddate : String,
    billMonth : String,
    billYear : String,
    utility : String,
    zone : String,
    region : String,
    billnumber : String,
    gstnumber : String,
    connectedload : String,
    Contractdemand : String,
    connecteddate : String,
    Sourcefile : String,
    fixchargunit : String,
    seznsez : String,
    metermodelno : String,
}
module.exports= Bill_Gen;